# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: barodrig <barodrig@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/06/02 11:50:59 by barodrig          #+#    #+#              #
#    Updated: 2021/07/20 14:06:03 by barodrig         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3.9'

services:
  mariadb:
    restart: on-failure
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - 42inception
    env_file: ./requirements/.env

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wp:inception
    container_name: wordpress
    restart: on-failure
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file: 
      - ./requirements/.env
    networks:
      - 42inception

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    container_name: nginx
    restart: on-failure
    hostname: localhost
    ports:
      - "443:443"
    networks:
      - 42inception
    extra_hosts:
      - "barodrig.42.fr:127.0.0.1"
    env_file: 
      - ./requirements/.env
    volumes:
      - wordpress:/var/www/html/wordpress

networks:
  42inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /Users/barodrig/42/42inception/srcs/requirements/data/wordpress
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: /Users/barodrig/42/42inception/srcs/requirements/data/db
      o: bind
