version: '3.9'

services:
  mariadb:
    restart: on-failure
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - 42inception_2
    env_file: ./requirements/.env

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wp:inception
    container_name: wordpress
    restart: on-failure
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file: 
      - ./requirements/.env
    networks:
      - 42inception_1
      - 42inception_2

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    container_name: nginx
    restart: on-failure
    hostname: localhost
    ports:
      - "443:443"
    networks:
      - 42inception_1
    env_file: 
      - ./requirements/.env
    volumes:
      - wordpress:/var/www/html/wordpress

networks:
  42inception_1:
    driver: bridge
  42inception_2:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home//barodrig/data/wordpress
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/barodrig/data/db
      o: bind
