# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: barodrig <barodrig@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/06/02 11:50:59 by barodrig          #+#    #+#              #
#    Updated: 2021/06/11 13:03:44 by barodrig         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3'

services:
  mariadb:
    #restart: always

    build:
      context: ./mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MARIA_LOGIN: "${MARIA_LOGIN}"
      MARIA_PASSWORD: "${MARIA_PASS}"
    volumes:
      - ~/data/mariadb:/var/lib/mysql
    networks:
      alliance:
    env_file: .env

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    #restart: always
    ports:
      - "9000:9000"
    environment:
      MARIA_LOGIN: "${MARIA_LOGIN}"
      MARIA_PASSWORD: "${MARIA_PASS}"
      WP_LOGIN: "${WP_LOGIN}"
      WP_PASSWORD: "${WP_PASS}"
      WPU_1LOGIN: "${WPU_1LOGIN}"
      WPU_1PASS: "${WPU_1PASS}"
    volumes:
      - ~/data/wp:/var/wwww/wp
    networks:
      alliance:
    env_file: .env

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./nginx
      dockerfile: Dockerfile
    #restart: always
    ports:
      - "443:443"
    networks:
      alliance:
    extra_hosts:
      - "barodrig.42.fr:127.0.0.1"


volumes:
  data:
#    external: true

networks:
  alliance:
    driver: bridge
