# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: barodrig <barodrig@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/06/02 11:50:59 by barodrig          #+#    #+#              #
#    Updated: 2021/06/15 17:08:14 by barodrig         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3'

services:
  mariadb:
    restart: on-failure
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIA_LOGIN: "${MARIA_LOGIN}"
      MARIA_PASSWORD: "${MARIA_PASS}"
    volumes:
      - volume_mariadb:/var/lib/mysql
    networks:
      - 42inception
    env_file: .env

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: on-failure
    ports:
      - "9000:9000"
    environment:
      MARIA_LOGIN: "${MARIA_LOGIN}"
      MARIA_PASSWORD: "${MARIA_PASS}"
      WP_LOGIN: "${WP_LOGIN}"
      WP_PASSWORD: "${WP_PASS}"
      WPU_1LOGIN: "${WPU_1LOGIN}"
      WPU_1PASS: "${WPU_1PASS}"
    volumes:
      - volume_wordpress:/var/wwww/wp
    networks:
      - 42inception
    env_file: .env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - 42inception
    extra_hosts:
      - "barodrig.42.fr:127.0.0.1"
      - "www.barodrig.42.fr:127.0.0.1"

volumes:
  volume_wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/barodrig/data/wordpress
  volume_mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/barodrig/data/mariadb

networks:
  42inception:
    driver: bridge
