# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: barodrig <barodrig@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/06/02 11:50:59 by barodrig          #+#    #+#              #
#    Updated: 2021/06/10 16:28:56 by barodrig         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
    networks:
      - alliance
  wordpress:
    depends_on:
      - nginx
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ~/home/barodrig/data:/data
    networks:
      - alliance

volumes:
  data:
#    external: true

networks:
  alliance:
    driver: bridge
