# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: barodrig <barodrig@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/06/02 11:50:59 by barodrig          #+#    #+#              #
#    Updated: 2021/07/19 16:04:38 by barodrig         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3'

services:
  mariadb:
    restart: always
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIA_LOGIN: "${MARIA_LOGIN}"
      MARIA_PASSWORD: "${MARIA_PASS}"
      MARIA_DATABASE: "${MARIA_DATABASE}"
      MARIA_ROOT_PASSWORD: "${MARIA_ROOT_PASSWORD}"
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - 42inception
    env_file: .env

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    ports:
      - "9000:9000"
    environment:
      MARIA_LOGIN: "${MARIA_LOGIN}"
      MARIA_PASSWORD: "${MARIA_PASS}"
      WP_LOGIN: "${WP_LOGIN}"
      WP_PASSWORD: "${WP_PASS}"
      WPU_1LOGIN: "${WPU_1LOGIN}"
      WPU_1PASS: "${WPU_1PASS}"
      WP_TABLE_PREFIX: "${WP_TABLE_PREFIX}"
    volumes:
      - wordpress:/var/www/html/
    networks:
      - 42inception
    env_file: .env

  nginx:
    depends_on:
      - wordpress
      - mariadb
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - 42inception
    extra_hosts:
      - "barodrig.42.fr:127.0.0.1"
      - "www.barodrig.42.fr:127.0.0.1"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/mariadb'

networks:
  42inception:
    driver: bridge
